Desktop version
edubew/Capstone_project1 pull request #3
Opened 2022-05-20 13:13 UTC by edubew

# Capstone1 Project (Desktop Version)
- Add media queries to make the page responsive for all screen sizes
- Link the about page and logo to the home page 
- Added functionality on the hamburger menu such that it displays the nav items when clicked
- Added the featured speaker section dynamically with javascript
- Recorded a 5-minute loom video describing the main features of the project
- Deployed the page with GitHub pages
- Check to see that everything is working as planned

2022-05-20 19:34 UTC, rloterh requested changes
Hi Edube, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Descriptive Pull Request
- Correct gitflow implemented
- Nice to acknowledge [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 19:34 UTC, rloterh commented on index.html
>          <ul class="navbar-links hide">
- [x] The red thick border around the _campaign_ text on the _white navbar_ is missing. Kindly ensure to add the same and it should be vertically aligned right with the _Logout_ menu item on the dark navbar. Remember we as much as possible want our design to mimic the given [template](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

**Your design:**
![image](https://user-images.githubusercontent.com/12745474/169592300-12666755-49cf-4495-af3b-2213ed1a92a7.png)

**The original design:**
![image](https://user-images.githubusercontent.com/12745474/169591974-bdc49fa0-67fd-41a0-94f8-4f007de6ebc2.png)

2022-05-20 19:34 UTC, rloterh commented on index.html
>      <section class="introductory-section">
- [x] The typography and line texts of your _hero_ section do not match the provided [desgn template](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). We actually want our design to as much as possible closely mimic the design of the provided template. The Home page should contain a _top_ section with a column that includes a **small line of text**, **the page title**, a **block of text**, a **medium line of text in bold letters**, and a **smaller line of text**, as can be seen in the provided template design. Let's ensure that the **font family**, font sizes, **font weights**, **font colors**, and **letter-spacing** match that of the provided template design. Also, ensure that the content in this section is centered horizontally (the extreme top and bottom space should be equal).

**Your hero design:**
![image](https://user-images.githubusercontent.com/12745474/169593689-2cd1c5f9-87a7-4c89-a18a-bf7186b7b38a.png)


**The original hero design:**
![image](https://user-images.githubusercontent.com/12745474/132607606-41b0af31-fa67-4194-8d5d-5874348ab4d8.png)

2022-05-20 19:34 UTC, rloterh commented on index.html
>      <section class="events-section">
The spacing of your main program section does not follow the [template design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). Kindly ensure to improve upon the following:
- [ ]  Contents in this section should have appropriate padding all around them. (See the indication from the attached screenshot)
- [ ] The _link_ below the content of this section, _see the whole program_ should be in **uppercase**.
**Your main program section:**
![image](https://user-images.githubusercontent.com/12745474/169594860-43c5cab5-cf8a-45df-a516-4398acf70b0c.png)


**The original main program section:**
![image](https://user-images.githubusercontent.com/12745474/169595746-df4272f5-3f63-4487-9406-4c406e41eb72.png)

2022-05-20 19:34 UTC, rloterh commented on index.html
>      <section class="featured-speaker-section">
The spacing/ alignment of your Featured Speakers sections does not match the provided design. Kindly note that we actually want this design to as much as possible mimic the provided  [design template](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). Kindly ensure to improve upon the following:
- [ ] Add background decoration around each image
- [ ] Shapes of images should appear more of a square
- [ ] Ensure there are appropriate paddings around the elements of each content, as can be seen in the design template 
- [ ] Ensure that the contents are spaced appropriately, as can be seen in the design template:

**Your Featured speakers section:**
![image](https://user-images.githubusercontent.com/12745474/169597241-093f0a04-ea00-4eef-ab45-98f13c4b90dc.png)


**The original Featured speakers section:**
![image](https://user-images.githubusercontent.com/12745474/138319005-e3205012-0f6f-4535-ad6e-06f08229e3b9.png)

2022-05-20 19:34 UTC, rloterh commented on index.html
> +      <div class="social-links hide">
- [ ] The mobile menu is missing from your mobile design screen. Kindly ensure to add a hamburger menu on the left side of the navigation for the mobile screen, which should display the mobile menu when clicked

2022-05-20 19:34 UTC, rloterh commented on script.js
> +    <img src="images/${speaker.featuredImage}" alt="">
- [ ] OPTIONAL
It's a good practice to provide `alt` names for your images so as to improve the accessibility features of your site.  Kindly endeavor to add `alt` names to **all** your images.

2022-05-21 10:15 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @edubew , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Decriptive readme file.
:heavy_check_mark: Clean code.

### Optional suggestions :arrow_down_small: 

- [x] The commit message should be written in the imperative tense. `Ex: "Fix bug" instead of "Fixed bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-21 10:25 UTC, merged